# action to build and push docker image on release
name: Build and push Docker image on release

on:
    release:
        types:
            - created

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            # login to github container registry 
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # build and push docker image
            - name: Build and push docker image
              uses: docker/build-push-action@v4
              with:
                  file: .docker/Dockerfile.prod
                  context: .
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository_owner }}/password-and-hash-generator:${{ github.event.release.tag_name }}
                      ghcr.io/${{ github.repository_owner }}/password-and-hash-generator:latest
