# action workflow to build and push docker image on release
name: Build and push Docker image on release

# on:
#     release:
#         types: [published]

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            # setup node
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22

            # install dependencies
            - name: Install dependencies
              run: npm install

            # build app
            - name: Build React app
              run: npm run build

            # login to github container registry
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # build docker image
            - name: Build Docker image
              run: |
                  IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/password-and-hash-generator:latest
                  docker build -t $IMAGE_TAG .

            # push docker image
            - name: Push Docker image
              run: |
                  IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/password-and-hash-generator:latest
                  docker push $IMAGE_TAG
