# static code analyse with eslint
name: ESLint

on:
  push:
    branches:
      - main
      - dev

jobs:
  eslint:
    name: ESLint analyse
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # setup nodejs
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # install dependencies with npm
      - name: Install dependencies
        run: npm install

      # ESLint process
      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx
